### ISSUE TITLE
Random Canon Titles 83-84

### ISSUE THREAD

**Issue by riddella** [random-canon/random-canon#111]
Be sure to use the first edition.

```
83. (#11201) Sigerson’s A Ruined Race (1889), 1 volume, British Library
23 chapters
11201__chp4of23_seed11201.html

84. (#6802) Murray’s A Man of Genius (1895), 2 volumes, British Library
4 + 4=8 chapters (warning: seriously long chapters
6802__chp2of8_seed6802.html
```

**Comment by riddella** [comment]
Hi @sduke do you mind if someone else grabs this task? (New texts will be posted soon.)

**Comment by sduke** [comment]
Absolutely, someone else is welcome to take it!

**Comment by hanmills** [comment]
Is this one still up for grabs?

**Comment by riddella** [comment]
Yes, please take it.

**Comment by riddella** [comment]
Note for @riddella Sigerson belongs at index 79 with the corrected numbering.

**Comment by riddella** [comment]
Another note for @riddella , Murray index is correct at 84.

**Comment by riddella** [comment]
@hanmills just checking in. Are you still working on these two?

**Comment by hanmills** [comment]
@riddella Yes they will be finished this weekend.

**Comment by riddella** [comment]
Great! These are among the last few we need to reach 100 titles.

**Comment by hanmills** [comment]
[6802__murray_a_man_of_genius_chp2of8_seed6802.txt](https://github.com/random-canon/random-canon/files/3516086/6802__murray_a_man_of_genius_chp2of8_seed6802.txt)
[11201__sigersons_a_ruined_race_chp4of23_seed11201.txt](https://github.com/random-canon/random-canon/files/3516087/11201__sigersons_a_ruined_race_chp4of23_seed11201.txt)
