### ISSUE TITLE
Reprint Canon Titles 71 72 (correct numbering)

### ISSUE THREAD

**Issue by riddella** [random-canon/random-canon#129]
These are Reprint Canon titles, any edition is OK.

- THE PRINCESS AND THE GOBLIN ``8813__macdonald_princess_goblin_chp26of32_seed8813.html`` url https://www.gutenberg.org/files/34339/34339-h/34339-h.htm
- David Copperfield ``7469__dickens_david_copperfield_chp2of64_seed7469.html`` url https://www.gutenberg.org/files/766/766-h/766-h.htm

**Comment by leschnei** [comment]
[MacDonald.txt](https://github.com/random-canon/random-canon/files/3311050/MacDonald.txt)

**Comment by leschnei** [comment]
[Copperfield.txt](https://github.com/random-canon/random-canon/files/3336249/Copperfield.txt)
