### ISSUE TITLE
Random Canon titles 99,100

### ISSUE THREAD

**Issue by riddella** [random-canon/random-canon#135]
Remember to use first edition page images

```
99. 1838-m
(#7400) Ware’s The Last Days of Aurelian, 2 volumes, Google books, Hathitrust (publisher Bentley)
11 chapters/letters (continuously numbered) (long chapters); first title
7400__chp8of11_seed7400.html

100. 1875-w
(#5225) Clarke’s Strong as Death, 3 volumes, British Library
11+ 12+12=35 chapters; second title (1 selected)
5225__chp7of35_seed5225.html
```

**Comment by leschnei** [comment]
[Ware.txt](https://github.com/random-canon/random-canon/files/3438347/Ware.txt)

**Comment by leschnei** [comment]
I'm having some difficulty finding the second title. At The Circulating Library directs me to the same title by a different author

**Comment by riddella** [comment]
Hi @leschnei Looks like Troy indicated this one is only at the british library. Have you entered one from there before? The ATCL record is this one: http://www.victorianresearch.org/atcl/show_title.php?tid=5225&aid=1784

**Comment by leschnei** [comment]
@riddella unfortunately that one seems to take me to the one by Guy de Maupassant...

**Comment by ayarnell** [comment]
@leschnei Try this link:  http://access.bl.uk/item/viewer/ark:/81055/vdc_00000004A1EA#?c=0&m=0&s=0&cv=3&xywh=-904%2C-1%2C4311%2C1969

**Comment by ayarnell** [comment]
@leschnei Here is the PDF of Chapter 7 from British Library. It's not a super intuitive site to use. [Digital Store 12634.n.1._Strong as Death Collection Item_extract.pdf](https://github.com/random-canon/random-canon/files/3438745/Digital.Store.12634.n.1._Strong.as.Death.Collection.Item_extract.pdf)

**Comment by ayarnell** [comment]
@riddella The Ware chapter #7400 is in PR #147

**Comment by leschnei** [comment]
Awesome Amy, thanks! I tried searching there as indicated and had no luck--how were you able to find it?

**Comment by ayarnell** [comment]
@leschnei No prob! I searched the main catalog for Clarke Strong as Death. It came up as the first option, BUT you have to select the "I want this" tab to get the link to the digital version. Otherwise it is kind of hidden.

**Comment by leschnei** [comment]
[StrongasDeath.txt](https://github.com/random-canon/random-canon/files/3521570/StrongasDeath.txt)

**Comment by leschnei** [comment]
[StrongasDeath.txt](https://github.com/random-canon/random-canon/files/3521683/StrongasDeath.txt)

Previous attachment left out author at beginnign

**Comment by ayarnell** [comment]
@riddella Title 100 in PR #159
