### ISSUE TITLE
Random Canon replacement for sample index 88 

### ISSUE THREAD

**Issue by riddella** [random-canon/random-canon#150]
Please be sure to use the first edition.

```
> 1887-u, BTAO “My Trivial Life and Misfortunes”, Poor Nellie (3 volumes), 
> in Hathitrust
> 21+20+24=65 chapters
> 811__chp6of65_seed811.html
```

**Comment by leschnei** [comment]
Regarding the instruction, Encode a redaction using ⸺. In Unicode this character has the following name: ⸺ U+2E3A TWO-EM DASH (omission dash):

Do I just enter "⸺ U+2E3A"?

**Comment by riddella** [comment]
Just the "⸺" (without quotation marks). You should be able to cut and paste it into the text, just as one would cut and paste some other sort of special character that's difficult/impossible to type on a US keyboard (e.g., ¾, ǫ).

**Comment by riddella** [comment]
I think this is the very last text before we hit 100. :100:

**Comment by leschnei** [comment]
[PoorNellie.txt](https://github.com/random-canon/random-canon/files/3538391/PoorNellie.txt)
Wahoo!!

**Comment by ayarnell** [comment]
@riddella 811 in PR #163
