### ISSUE TITLE
Reprint Canon 89, 90

### ISSUE THREAD

**Issue by riddella** [random-canon/random-canon#153]
These are two Reprint Canon Titles. Feel free to use Gutenberg for this.

89 | Kipling | Stalky and Co. | 1899 | 9109__kipling_stalky_chp4of9_seed9109.html section/chapter is “ THE IMPRESSIONISTS. “
-- | -- | -- | -- | --
90 | Wells | The Invisible Man | 1897 | 8594__wells_invisible_man_chp16of29_seed8594.html (29 chapters, including epilogue)

**Comment by ayarnell** [comment]
@riddella Reprint titles 89 and 90 in PR #159
