### ISSUE TITLE
Reprint Canon 91,92

### ISSUE THREAD

**Issue by riddella** [random-canon/random-canon#154]
These are two Reprint Canon Titles. Feel free to use Gutenberg for this.

91 | Trollope | Phineas Redux | 1874 | 5781__trollope_phineas_redux_chp7of80_seed5781.html
-- | -- | -- | -- | --
92 | Stevenson | The Black Arrow | 1888 | 7927__stevenson_black_arrow_chp18of33_seed7927.html 33 chps counting the prologue, chp 18 should be chapter 3 of book 3 CHAPTER III—ST. BRIDE’S CROSS

**Comment by ayarnell** [comment]
@riddella Texts in PR #160
