### ISSUE TITLE
Reprint Canon 93,94

### ISSUE THREAD

**Issue by riddella** [random-canon/random-canon#155]
These are Reprint Canon Titles. Feel free to use Gutenberg for this.

93 | James | The Awkward Age | 1899 | 7962__james_awkward_age_chp9of38_seed7962.html chapter 9 should be the final chapter of book 2
-- | -- | -- | -- | --
94 | Craik | John Halifax, Gentleman | 1856 | 3700__craik_john_halifax_chp2of40_seed3700.html

**Comment by ayarnell** [comment]
@riddella Texts 3700 and 7962 are in PR #162
