### ISSUE TITLE
Reprint Canon 95,96,97

### ISSUE THREAD

**Issue by riddella** [random-canon/random-canon#156]
These are Reprint Canon Titles. Feel free to use Gutenberg for this.

95 | Trollope | The Warden | 1855 | 7448__trollope_the_warden_chp18of21_seed7448.html
-- | -- | -- | -- | --
96 | Wilde | A House of Pomegranates | 1891 | 9112__wilde_house_pomegranates_chp2of4_seed9112.html
97 | Cooper | The Deerslayer | 1841 | 3203__cooper_deerslayer_chp14of33_seed3203.html

**Comment by leschnei** [comment]
[Warden.txt](https://github.com/random-canon/random-canon/files/3586740/Warden.txt)

**Comment by ayarnell** [comment]
@riddella Texts 7448, 9112, and 3203 in PR #163
