### ISSUE TITLE
Add next 10 "reprint canon" titles

### ISSUE THREAD

**Issue by riddella** [random-canon/random-canon#2]
Here are the next 10 titles to add to the "reprint canon":

- [x] James	The Spoils of Poynton	1897: 7958__james_poynton_chp17of22_seed7958.html
- [x] Gaskell	The Grey Woman and Other Tales: 7705__gaskell_grey_woman_chp4of12_seed7705.html (12 distinct "sections", 4 is the entire section titled "CURIOUS IF TRUE.")
- [x] Trollope	Orley Farm	1862: 7012__trollope_orley_farm_chp60of80_seed7012.html
- [x] Oliphant Hester 1883 864__oliphant_hester_chp10of16_seed864.html
- [x] Marsh	The Beetle	1897 8837__marsh_beetle_chp22of48_seed8837.html
- [x] Gaskell	Wives and Daughters	1866 5436__gaskell_wives_daughters_chp27of60_seed5436.html
- [x] Gaskell	Sylvia's Lovers	1863 261__gaskell_sylvias_lovers_chp28of45_seed261.html
- [x] Ward	Marcella	1894 4789__ward_marcella_chp44of47_seed4789.html
- [x] Eliot	Adam Bede	1859 3037__eliot_bede_chp41of56_seed3037.html
- [x] Hardy	The Return of the Native	1878 2191__hardy_return_native_chp11of48_seed2191.html

All titles are on Project Gutenberg. The randomly sampled chapter (or section, in one case) is indicated in the filename.

**Comment by riddella** [comment]
@ayarnell There's absolutely no rush here. I've listed 10 as this is just the way we've been doing things (i.e., 10 at a time).

**Comment by ayarnell** [comment]
@riddella Thanks! I did the first one 7958__james_poynton_chp17of22_seed7958.html and tried to add it, but I think it only got added to my fork? I am a little confused on how to add it to the main repository I think.

**Comment by riddella** [comment]
(I'm just seeing this now; I'll update my email settings so I get these messages sooner.)

Try going to https://github.com/ayarnell/random-canon and clicking on "pull request" (on the right hand side).

It does look like the main repository and your fork are out of sync. You probably need to do something like ``git pull --rebase``. We can go over this in person if you encounter trouble. (This describes the process: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request )

**Comment by ayarnell** [comment]
@riddella  Thanks! I did the pull request. I think the rebase also worked. I've never actually used git in the command line before, but the article you linked to was pretty clear. Let me know if it did actually work!

**Comment by riddella** [comment]
All entered.
