### ISSUE TITLE
Random canon titles 48, 49, 50

### ISSUE THREAD

**Issue by riddella** [random-canon/random-canon#33]
- [x] 4844 Egerton Castle, Consequences (1891) Google Books, Hathitrust?;  8 + 27 = 35 chapters; 4844__castle_consequences_chp9of35_seed4844.html
- [x] 12115 John Hutcheson, Afloat at Last (1890) PG; 17 chapters; 12115__hutcheson_afloat_chp3of17_seed12115.html
- [x] 2623 James Payn, A Woman’s Vengeance (1872) Hathitrust; 44 chapters; 2623__payn_chp38of44_seed2623.html

**Comment by hanmills** [comment]
Here's the next batch.
[castleconsequences.txt](https://github.com/random-canon/random-canon/files/2611992/castleconsequences.txt)
[hutchesonafloatatlast.txt](https://github.com/random-canon/random-canon/files/2611993/hutchesonafloatatlast.txt)
[paynawomansvengeance.txt](https://github.com/random-canon/random-canon/files/2611994/paynawomansvengeance.txt)

**Comment by riddella** [comment]
@hanmills Thanks for these. There's more at #38 !

**Comment by ayarnell** [comment]
@hanmills Based on your comment in the text for payn, citing illegible words on page 238, I think you used this [Leipzig edition](https://catalog.hathitrust.org/Record/011405700?type%5B%5D=all&lookfor%5B%5D=payn%20woman%27s%20vengeance&ft=ft) 
I think what we actually want is [this one]( https://catalog.hathitrust.org/Record/008724340?type%5B%5D=all&lookfor%5B%5D=payn%20woman%27s%20vengeance&ft=ft ) published in London.  @riddella Please correct me if I'm wrong.
By my count, the 38th chapter is then Chapter 9 of Vol. 3 "The Vision".

**Comment by ayarnell** [comment]
@riddella Pull request #42 contains 4844 and 12115.

**Comment by hanmills** [comment]
@ayarnell Sorry about that - here is the correct text. 
[paynawomansvengeancethevision.txt](https://github.com/random-canon/random-canon/files/2627707/paynawomansvengeancethevision.txt)

**Comment by ayarnell** [comment]
@hanmills Thanks! @riddella Text 2623 is in pull request #44
