### ISSUE TITLE
Add next 10 random canon titles (41-47)

### ISSUE THREAD

**Issue by riddella** [random-canon/random-canon#6]
Random Canon #41 to 47

- [x] 15770 R. D. Chetwode, The Knight of the Golden Chain (1898) Hathitrust US edition; 34 chapters; 15770__chetwode_knight_chp9of34_seed15770.html
- [x] 1054 Mrs. Alexander, A Crooked Path (1889) PG, Hathitrust; 36 chapters; 1054__alexander_crooked_chp5of36_seed1054.html
- [x] 4651 George Gissing, The Emancipated (1890) PG, Hathitrust; 16 + 17 = 33 chapters; 4651__gissing_emancipated_chp23of33_seed4651.html
- [x] 4691 Leslie Keith [Johnston], Lisbeth (1893) Hathitrust; 40 chapters; 4691__johnston_lisbeth_chp19of40_seed4691.html
- [x] 5683 Henry Spicer, Bound to Please (1867) Hathitrust, 25 stories, 5683__spicer_bound_chp9of25_seed5683.html
- [x] 8557 Guy Boothby, Long Live the King (1900) PG, Hathitrust; 22 chapters; 8557__boothby_chp2of22_seed8557.html
- [x] 4040 Anonymous, Sin and Sorrow (1850) Hathitrust; 15 + 21 + 20 = 56 chapters; 4040__anon_sin_chp4of56_seed4040.html

**Comment by riddella** [comment]
Assigned to LS.

**Comment by leschnei** [comment]
Chetwode completed

**Comment by leschnei** [comment]
Mrs. Alexander completed
[Mrs.Alexander.txt](https://github.com/random-canon/random-canon/files/2521400/Mrs.Alexander.txt)

**Comment by ayarnell** [comment]
@riddella Pull request opened for 1054 Mrs. Alexander

**Comment by leschnei** [comment]
[Gissing.txt](https://github.com/random-canon/random-canon/files/2545411/Gissing.txt)

**Comment by ayarnell** [comment]
@riddella Pull request opened for 4651 Gissing.

**Comment by riddella** [comment]
@leschnei I've taken three from the bottom of the list. If you've already started on them, let me know.

**Comment by leschnei** [comment]
I haven’t—thanks for the head’s up!

Laura

**Comment by leschnei** [comment]
Keith completed
[Keith.txt](https://github.com/random-canon/random-canon/files/2591435/Keith.txt)

**Comment by ayarnell** [comment]
@riddella Pull Request #35 contains Keith.

**Comment by ayarnell** [comment]
@riddella Spicer part of pull request #36

**Comment by ayarnell** [comment]
Last two of this batch are in pull request #49.
