### ISSUE TITLE
Reprint Canon titles 58-61

### ISSUE THREAD

**Issue by riddella** [random-canon/random-canon#84]
Project Gutenberg is fine for these.

- [x] Hardy Under the Greenwood Tree several parts, chapter 21 is chapter 4 of "Part the Third": ``7498__hardy_under_greenwood_tree_chp21of30_seed7498.html``
- [x] Trollope, Doctor Thorne chp 7 ``4122__trollope_doctor_thorne_chp7of47_seed4122.html``
- [x] Trollope, Small House at Allington ``5496__trollope_small_house_allington_chp18of60_seed5496.html``
- [x] Hardy, Jude the Obscure chp 52 is the second to last chapter, so chapter 10 in part 6 ``7499__hardy_jude_obscure_chp52of53_seed7499.html``

**Comment by ayarnell** [comment]
@riddella Opened PR #87 for these titles.
